config/routes.rb
Rails.application.routes.draw do
  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

  root 'store#index', as: 'store'

  devise_for :users, path: "auth", path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification',
    unlock: 'unblock', registration: 'register'}
end

app/models/attribute.rb
class Attribute < ActiveRecord::Base
  has_many :product_attributes
  has_many :products, through: :product_attributes
  has_one :attribute_description

  belongs_to :product_attribute
  belongs_to :attribute_group

  attr_accessor :sort_order
end

app/models/attribute_group.rb
class AttributeGroup < ActiveRecord::Base
  has_many :attributes
  has_one :attribute_group_description
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    logger.debug("Current item object: #{current_item.inspect}")
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_one :category_descriptions
  has_many :categorizations
  has_many :products, through: :categorizations
  # Self join on "parent_id" for category hierarchy
  has_many :subcategories, class_name: "Category",
                           foreign_key: "parent_id"
  belongs_to :parent, class_name: "Category"

  validates :image, presence: :ture
  validates :image, allow_blank: :true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: "must be an url for GIF, JPG or PNG image."
  }          
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :products

  validates :name, :image, presence: :true
  validates :image, allow_blank: :true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: "must be an url for GIF, JPG or PNG image."
  }
end

app/models/option.rb
class Option < ActiveRecord::Base
end

app/models/option_value.rb
class OptionValue < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_one :product_description
	has_many :product_images
	has_many :reviews
	has_many :product_attributes
	has_many :general_attributes, through: :product_attributes
	has_many :categorizations
	has_many :categories, through: :categorizations
	belongs_to :manufacturer
	has_many :line_items

	before_destroy :ensure_not_referenced_by_any_line_item

	validates :model, :sku, :mpn, :upc, :ean, :jan, :isbn, :location, :quantity, :image, :shipping,
	  :price, :points, :date_available, :minimum, :status, :viewed, presence: :ture
	validates :sku, uniqueness: :true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :image, allow_blank: :true, format: {
		with: %r{\.(gif|jpg|png)\Z}i,
		message: "must be an url for GIF, JPG or PNG image."
	}

	def self.latest
		Product.order(:updated_at).last
	end

	private

		# ensure that there are no line items referencing this product
		def ensure_not_referenced_by_any_line_item
			if line_items.empty?
				return true
			else
				errors.add(:base, 'Line Items present')
				return false
			end		
		end
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product

  validates :image, presence: :true
  validates :image, allow_blank: :true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: "must be an url for GIF, JPG or PNG image."
  }
end

app/models/product_option.rb
class ProductOption < ActiveRecord::Base
end

app/models/product_reward.rb
class ProductReward < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  # belongs_to :customer

  validates :author, :text, presence: :true
end

app/models/stock_status.rb
class StockStatus < ActiveRecord::Base
  belongs_to :product

  validates :name, presence: :true
end

app/models/tax_class.rb
class TaxClass < ActiveRecord::Base
end

app/models/tax_rate.rb
class TaxRate < ActiveRecord::Base
end

app/models/tax_rule.rb
class TaxRule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @product }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params[:product]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :model %>
  <%= f.input :sku %>
  <%= f.input :mpn %>
  <%= f.input :upc %>
  <%= f.input :ean %>
  <%= f.input :jan %>
  <%= f.input :isbn %>
  <%= f.input :location %>
  <%= f.input :quantity %>
  <%= f.input :image %>
  <%= f.input :shipping %>
  <%= f.input :price %>
  <%= f.input :points %>
  <%= f.input :date_available %>
  <%= f.input :weight %>
  <%= f.input :length %>
  <%= f.input :width %>
  <%= f.input :subtract %>
  <%= f.input :minimum %>
  <%= f.input :sort_order %>
  <%= f.input :status %>
  <%= f.input :viewed %>
  <%= f.input :stock_status_id %>
  <%= f.input :manufacturer_id %>
  <%= f.input :tax_class_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:model) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:points) %></th>
      <th><%= model_class.human_attribute_name(:date_available) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.model %></td>
        <td><%= image_tag(product.image, class: 'list_image') %></td>
        <td><%= product.price %></td>
        <td><%= product.points %></td>
        <td><%= product.date_available %></td>
        <td><%=l product.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
  <dd><%= @product.model %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sku) %>:</strong></dt>
  <dd><%= @product.sku %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mpn) %>:</strong></dt>
  <dd><%= @product.mpn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:upc) %>:</strong></dt>
  <dd><%= @product.upc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ean) %>:</strong></dt>
  <dd><%= @product.ean %></dd>
  <dt><strong><%= model_class.human_attribute_name(:jan) %>:</strong></dt>
  <dd><%= @product.jan %></dd>
  <dt><strong><%= model_class.human_attribute_name(:isbn) %>:</strong></dt>
  <dd><%= @product.isbn %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @product.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:quantity) %>:</strong></dt>
  <dd><%= @product.quantity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @product.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:shipping) %>:</strong></dt>
  <dd><%= @product.shipping %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:points) %>:</strong></dt>
  <dd><%= @product.points %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date_available) %>:</strong></dt>
  <dd><%= @product.date_available %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weight) %>:</strong></dt>
  <dd><%= @product.weight %></dd>
  <dt><strong><%= model_class.human_attribute_name(:length) %>:</strong></dt>
  <dd><%= @product.length %></dd>
  <dt><strong><%= model_class.human_attribute_name(:width) %>:</strong></dt>
  <dd><%= @product.width %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subtract) %>:</strong></dt>
  <dd><%= @product.subtract %></dd>
  <dt><strong><%= model_class.human_attribute_name(:minimum) %>:</strong></dt>
  <dd><%= @product.minimum %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sort_order) %>:</strong></dt>
  <dd><%= @product.sort_order %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @product.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:viewed) %>:</strong></dt>
  <dd><%= @product.viewed %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stock_status_id) %>:</strong></dt>
  <dd><%= @product.stock_status_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:manufacturer_id) %>:</strong></dt>
  <dd><%= @product.manufacturer_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tax_class_id) %>:</strong></dt>
  <dd><%= @product.tax_class_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <%= button_to "Add to Cart", line_items_path(product_id: @product), :class => "btn btn-success pull-right" %>
</div>